a = LU

In [3]:
import numpy as np
from scipy.linalg import lu

A = np.array([[4, 3, -2], [2, 1, 1], [3, -2, 4]])

# LU-разложение (с частичным выбором главного элемента)
P, L, U = lu(A)  # P — матрица перестановок

print("P (permutation):\n", P)
print("L (lower triangular):\n", L)
print("U (upper triangular):\n", U)

# Проверка: A = P @ L @ U
print("A == P @ L @ U:\n", np.allclose(A, P @ L @ U))

P (permutation):
 [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
L (lower triangular):
 [[1.         0.         0.        ]
 [0.75       1.         0.        ]
 [0.5        0.11764706 1.        ]]
U (upper triangular):
 [[ 4.          3.         -2.        ]
 [ 0.         -4.25        5.5       ]
 [ 0.          0.          1.35294118]]
A == P @ L @ U:
 True


a = QR

In [4]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# QR-разложение (метод Хаусхолдера)
Q, R = np.linalg.qr(A)

print("Q (orthogonal):\n", Q)
print("R (upper triangular):\n", R)

# Проверка: A = Q @ R
print("A == Q @ R:\n", np.allclose(A, Q @ R))

Q (orthogonal):
 [[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
R (upper triangular):
 [[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -8.88178420e-16]]
A == Q @ R:
 True


A = LL^T

In [5]:
import numpy as np

# Только для симметричных положительно определённых матриц!
A = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]])

# Разложение Холецкого: A = L @ L.T
L = np.linalg.cholesky(A)

print("L (lower triangular):\n", L)

# Проверка: A == L @ L.T
print("A == L @ L.T:\n", np.allclose(A, L @ L.T))

L (lower triangular):
 [[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]
A == L @ L.T:
 True


SVD

In [6]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# SVD: A = U @ Σ @ V.T
U, S, Vt = np.linalg.svd(A)

# Σ возвращается как вектор, преобразуем в диагональную матрицу
Sigma = np.zeros_like(A, dtype=float)
Sigma[:len(S), :len(S)] = np.diag(S)

print("U (left singular vectors):\n", U)
print("Σ (singular values):\n", Sigma)
print("Vt (right singular vectors, transposed):\n", Vt)

# Проверка: A = U @ Σ @ Vt
print("A == U @ Σ @ Vt:\n", np.allclose(A, U @ Sigma @ Vt))

U (left singular vectors):
 [[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
Σ (singular values):
 [[1.68481034e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.06836951e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 4.41842475e-16]]
Vt (right singular vectors, transposed):
 [[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]
A == U @ Σ @ Vt:
 True


$$QTQ^{Q}$$

In [7]:
import numpy as np
from scipy.linalg import schur

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Разложение Шура: A = Q @ T @ Q.T
T, Q = schur(A)

print("Q (unitary):\n", Q)
print("T (quasi-upper triangular):\n", T)

# Проверка: A = Q @ T @ Q.T
print("A == Q @ T @ Q.T:\n", np.allclose(A, Q @ T @ Q.T))

Q (unitary):
 [[-0.23197069 -0.88290596  0.40824829]
 [-0.52532209 -0.23952042 -0.81649658]
 [-0.8186735   0.40386512  0.40824829]]
T (quasi-upper triangular):
 [[ 1.61168440e+01  4.89897949e+00  1.58820582e-15]
 [ 0.00000000e+00 -1.11684397e+00 -1.11643184e-15]
 [ 0.00000000e+00  0.00000000e+00 -1.30367773e-15]]
A == Q @ T @ Q.T:
 True


полярное разложение

In [9]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=float)

# Вычисляем SVD: A = U Σ V^T
U, S, Vt = np.linalg.svd(A)

# P = V^T * Σ * V (эрмитова положительно полуопределённая матрица)
P = (Vt.T * S) @ Vt  # Эквивалентно: Vt.T @ np.diag(S) @ Vt

# U (унитарная матрица) = U * V^T
U_polar = U @ Vt

print("U (unitary):\n", U_polar)
print("P (positive semi-definite):\n", P)

# Проверка: A ≈ U @ P (из-за численных погрешностей используем allclose)
print("A ≈ U @ P:", np.allclose(A, U_polar @ P, atol=1e-10))

U (unitary):
 [[-0.75271952  0.38914789  0.5310153 ]
 [ 0.38914789 -0.38759388  0.83566435]
 [ 0.5310153   0.83566435  0.1403134 ]]
P (positive semi-definite):
 [[4.52097913 4.68842281 4.85586648]
 [4.68842281 5.52564116 6.36285952]
 [4.85586648 6.36285952 7.86985257]]
A ≈ U @ P: True


Жорданова нормальная форма

In [ ]:
from sympy import Matrix

A = Matrix([[4, 1, -1], [0, 3, 0], [1, 0, 2]])

# Жорданова форма: A = P @ J @ P⁻¹
P, J = A.jordan_form()

print("P (transition matrix):\n", P)
print("J (Jordan form):\n", J)

# Проверка: A == P @ J @ P⁻¹
print("A == P @ J @ P⁻¹:\n", A == P @ J @ P.inv())